FreeDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('', include('project.urls')),
]


main/urls.py
from django.urls import path
from . import views
from django.conf.urls import url


urlpatterns = [
    path('', views.index, name='home'),
    path('about', views.about, name='about'),
    # path('add', views.add, name='add'),
]

project/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from .views import HousesAutocomplete
from .views import SuppliersAutocomplete
from dal import autocomplete
from .models import Goods
from .models import Object
from .models import House
from .models import Supplier

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'project'


class LinkedDataView(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return House.objects.none()

        qs = House.objects.all()
        object_ = self.forwarded.get('object', None)

        if object_:
            qs = qs.filter(object_id=object_)

        return qs


urlpatterns = [
    url(
        r'^goods-autocomplete/$',
        autocomplete.Select2QuerySetView.as_view(model=Goods),
        # GoodsAutocomplete.as_view(),
        name='select_goods',
    ),
    url(
        r'^objects-autocomplete/$',
        autocomplete.Select2QuerySetView.as_view(model=Object),
        # GoodsAutocomplete.as_view(),
        name='select_object',
    ),
    url(
        r'^houses-autocomplete/$',
        # autocomplete.Select2QuerySetView.as_view(model=House),
        HousesAutocomplete.as_view(),
        name='select_house',
    ),
    url(
        r'^suppliers-autocomplete/$',
        #autocomplete.Select2QuerySetView.as_view(model=Supplier),
        #SuppliersAutocomplete.as_view(create_field='name'),
        SuppliersAutocomplete.as_view(),
        name='select_supplier',
    ),
    url(
        r'^suppliers-autocomplete-view/$',
        SuppliersAutocomplete.as_view(),
        name='select_supplier_view',
    ),
    url(
        '^linked_data/$',
        LinkedDataView.as_view(model=House),
        name='linked_data'
    ),

    path('requests/<int:request_id>/add/', views.details_add, name='detailsadd'),
    path('requests/<int:request_id>/', views.one_request, name='onerequest'),
    path('requests/add', views.new_request, name='newrequest'),
    path('requests/', views.requests, name='requests'),

    path('content/<int:content_id>/delete/', views.contents_delete, name='contentsdelete'),
    path('content/<int:content_id>/edit/', views.contents_edit, name='contentsedit'),
    path('content/<int:content_id>/copy/', views.contents_copy, name='contentscopy'),
    path('content/<int:content_id>/expense/', views.edit_expense_transaction, name='editexpensetransaction'),
    path('content/<int:content_id>/erase/', views.erase_expense_transaction, name='eraseexpensetransaction'),

    path('bids/<int:bid_id>/edit/', views.bid_edit, name='bidedit'),
    path('bids/<int:bid_id>/delete/', views.bid_del, name='biddel'),
    path('bids/<int:bid_id>/report/', views.bid_report, name='bidreport'),
    path('bids/<int:bid_id>/unlock/', views.bid_unlock, name='bidunlock'),
    path('bids/<int:bid_id>/mark/', views.bid_mark, name='bidmark'),
    path('bids/<int:bid_id>/unmark/', views.bid_unmark, name='bidunmark'),

    path('bids/<int:bid_id>/hide/', views.bid_hide, name='bidhide'),
    path('bids/<int:bid_id>/unhide/', views.bid_unhide, name='bidunhide'),

    path('bids/<int:bid_id>/refund/', views.bid_refund, name='bidrefund'),
    path('bids/<int:bid_id>/cancel/', views.bid_cancel_refund, name='bidcancelrefund'),

    path('bids/<int:bid_id>/sign/', views.bid_sign, name='bidsign'),
    path('bids/<int:bid_id>/lock/', views.bid_lock, name='bidlock'),
    path('bids/<int:bid_id>/add/', views.contents_add, name='contentsadd'),
    path('bids/<int:bid_id>/delivery/', views.bid_delivery, name='biddelivery'),
    path('bids/<int:bid_id>/', views.one_bid, name='onebid'),
    path('bids/add/', views.new_bid, name='newbid'),
    path('bids/', views.filtered_bids, name='bids'),

    path('contract/<int:contract_id>/image/<int:image_id>/', views.view_image, name='viewimage'),
    path('contract/<int:contract_id>/image/<int:image_id>/del/', views.delete_image, name='deleteimage'),

    path('turnover/<int:turnover_id>/goback/', views.turnover_return_perform, name='turnoverreturnperform'),
    path('turnover/<int:turnover_id>/bid/', views.turnover_bid_create, name='turnoverbidcreate'),
    path('turnover/<int:turnover_id>/expense/', views.turnover_expense, name='turnoverexpense'),
    path('turnover/<int:turnover_id>/delete/', views.turnover_delete, name='turnoverdelete'),
    path('turnover/<int:turnover_id>/accept/', views.turnover_accept, name='turnoveraccept'),
    path('turnover/<int:turnover_id>/return/', views.turnover_return, name='turnoverreturn'),
    path('turnover/<int:turnover_id>/perform/', views.edit_turnover_perform, name='turnovereditperform'),
    path('turnover/<int:turnover_id>/edit/', views.edit_turnover, name='turnoveredit'),
    path('turnover/<int:turnover_id>/comment/', views.edit_turnover_comment, name='turnovercommentedit'),
    path('contract/<int:contract_id>/report/', views.contract_report, name='contractreport'),
    path('contract/<int:contract_id>/return/', views.contract_return, name='contractreturn'),
    path('contract/<int:contract_id>/delete/', views.contract_delete, name='contractdelete'),
    path('contract/<int:contract_id>/open/', views.contract_open, name='contractopen'),
    path('contract/<int:contract_id>/performed/', views.contract_performed, name='contractperformed'),
    path('contract/<int:contract_id>/execute/', views.contract_execute, name='contractexecute'),
    path('contract/<int:contract_id>/onreserve/', views.contract_reservation, name='contractreservation'),
    path('contract/<int:contract_id>/unreserve/', views.contract_unreservation, name='contractunreservation'),
    path('contract/<int:contract_id>/reserve/', views.contract_reservation_accept, name='contractreserveaccept'),
    path('contract/<int:contract_id>/takeout/', views.contract_reservation_takeout, name='contractreservetakeout'),
    path('contract/<int:contract_id>/accept/', views.contract_accept, name='contractaccept'),
    path('contract/<int:contract_id>/turnover/', views.add_turnover, name='turnoveradd'),
    path('contract/<int:contract_id>/addimage/', views.add_checkimage, name='addcheckimage'),
    path('contract/<int:contract_id>/edit/', views.edit_contract, name='contractedit'),
    path('contract/<int:contract_id>/change/', views.change_contract, name='contractchange'),
    path('contract/<int:contract_id>/receipt/', views.receipt_contract, name='contractreceipt'),
    path('contract/<int:contract_id>/revoke/', views.revoke_contract, name='contractrevoke'),
    path('contract/<int:contract_id>/restore/', views.contract_restore, name='contractrestore'),
    path('contract/<int:contract_id>/', views.one_contract, name='onecontract'),
    path('contracts/add/', views.new_contract, name='contractadd'),
    path('contracts/', views.filtered_contracts, name='contracts'),

    path('contractsexport/', views.contracts_export, name='contractsexport'),
    path('bidsexport/', views.bids_export, name='bidsexport'),
    #path('transferobject/', views.transfer_object, name='transferobject'),
    #path('fill_delivered_bids/', views.fill_delivered_bids_, name='fill_delivered_bids'),
    #path('fill_performed_turnovers/', views.fill_performed_turnovers_, name='fill_performed_turnovers'),
    #path('fill_completed_contracts/', views.fill_completed_contracts_, name='fill_completed_contracts'),

    path('detail/<int:detail_id>/edit/', views.details_edit, name='detailsedit'),
    path('detail/<int:detail_id>/delete/', views.details_delete, name='detailsdelete'),
    path('archive/<int:arch_id>/delete/', views.arch_delete, name='archdelete'),
    path('archive/<int:arch_id>/edit/', views.arch_edit, name='archedit'),
    path('archive/<int:arch_id>/', views.one_archive_item, name='onearchiveitem'),
    path('archive/', views.archive, name='archive'),

    path('prepayment/<int:prepayment_id>/edit/', views.prepayment_edit, name='prepaymentedit'),
    path('prepayment/add/', views.new_prepayment, name='newprepayment'),
    path('concrete/<int:delivery_id>/edit/', views.concrete_delivery_edit, name='concretedeliveryedit'),
    path('concrete/<int:delivery_id>/delete/', views.concrete_delivery_delete, name='concretedeliverydelete'),
    path('concrete/add/', views.new_concrete_delivery, name='newdconcretedelivery'),
    path('concrete/', views.filtered_concrete_delivery, name='filteredconcretedelivery'),

    path('balances/', views.filtered_balances, name='filteredbalances'),
    path('subcash/<int:subcash_id>/edit/', views.edit_subcash, name='subcashedit'),
    path('subcash/add/', views.new_subcash, name='newsubcash'),
    path('subcash/', views.filtered_subcashes, name='filteredsubcashes'),

    path('earning/<int:earning_id>/edit/', views.edit_earning_transaction, name='editearningtransaction'),
    path('earning/add/', views.create_earning_transaction, name='newearning'),
    path('account/<int:account_id>/edit/', views.edit_account, name='accountedit'),
    path('account/add/', views.new_account, name='newaccount'),
    path('account/', views.filtered_accounts, name='filteredaccounts'),

    path('report/house/<int:house_id>/<int:estimate_id>/<int:phase_id>/<str:type>/<str:exclusion>/', views.house_estimate_report, name='houseestimatereport'),
    path('phasereport/house/<int:house_id>/<int:phase_id>/<int:estimate_id>/<str:type>/<str:exclusion>/', views.house_phase_report, name='housephasereport'),
    path('report/house/<int:house_id>/concrete/', views.house_concrete_report, name='houseconcretereport'),
    path('report/house/<int:house_id>/', views.house_report, name='housereport'),
    path('supplier/<int:supplier_id>/report', views.supplier_detail_xls_report, name='supplierdetailxlsreport'),


project/templates/project/addaccount.html
{% extends 'main/base.html' %}
{% load bootstrap5 %}
{% block title %}
{{ title }}
{% endblock %}

{% block content %}
    <form method="post" class="form" style="max-width: 25em; padding: 15px; width: 100%; margin: auto">
        {% csrf_token %}
        <h1 class="h3 fw-normal" style="margin-top: 10px; margin-bottom: 10px">Добавление нового счета</h1>

        {{ form.name.label_tag }}<br>
        {{ form.name }}
        {{ form.cashregister.label_tag }}<br>
        {{ form.cashregister }}
        {{ form.balance.label_tag }}<br>
        {{ form.balance }}
        {{ form.date.label_tag }}<br>
        {{ form.date }}
        {% if form.date.errors %}
            <div class="alert alert-danger fade show mt-0" role="alert">{{ form.date.errors }}</div>
        {% endif %}
        {{ form.closedate.label_tag }}<br>
        {{ form.closedate }}

        {{ form.media }}
        {% buttons %}
            <button name="submit"  class="w-100 btn btn-lg btn-primary" style="margin-top: 10px">Сохранить</button>
        {% endbuttons %}
    </form>
    <div class="d-flex justify-content-center">
            <a class="btn btn-sm btn btn-secondary" href="{% url 'project:filteredaccounts' %}?c={{ cashregister }}">&#x21b6; Вернуться</a>
    </div>

{% endblock content %}

project/templates/project/addestimatemodal.html
{% load bootstrap5 %}
{% load bootstrap_icons %}
{% load filters %}

<form method="post" action="">
  {% csrf_token %}
    <div class="modal-header" xmlns="http://www.w3.org/1999/html">
        <h5 class="modal-title">Добавление сметы</h5>
    </div>
    <div class="modal-body">
            {{ form.name.label_tag }}<br>
            {{ form.name }}
            <div class="mb-2 mt-3 form-check form-switch">
                Скрытая смета{{ form.hidden }}
            </div>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Возврат</button>
        <button type="submit" class="btn btn-warning">Создать</button>
    </div>
</form>

project/templates/project/addhousemodal.html
{% load bootstrap5 %}
{% load bootstrap_icons %}
{% load filters %}

<form method="post" action="">
  {% csrf_token %}
    <div class="modal-header" xmlns="http://www.w3.org/1999/html">
        <h5 class="modal-title">Добавление дома</h5>
    </div>
    <div class="modal-body">
            {{ form.name.label_tag }}<br>
            {{ form.name }}

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Возврат</button>
        <button type="submit" class="btn btn-warning">Создать</button>
    </div>
</form>

project/templates/project/addsubcash.html
{% extends 'main/base.html' %}
{% load bootstrap5 %}
{% block title %}
{{ title }}
{% endblock %}

{% block content %}
    <form method="post" class="form" style="max-width: 25em; padding: 15px; width: 100%; margin: auto">
        {% csrf_token %}
        <h1 class="h3 fw-normal" style="margin-top: 10px; margin-bottom: 10px">Добавление новой кассы</h1>

        {{ form.name.label_tag }}<br>
        {{ form.name }}
        {{ form.cashregister.label_tag }}<br>
        {{ form.cashregister }}
        {{ form.balance.label_tag }}<br>
        {{ form.balance }}
        {{ form.date.label_tag }}<br>
        {{ form.date }}
        {% if form.date.errors %}
            <div class="alert alert-danger fade show mt-0" role="alert">{{ form.date.errors }}</div>
        {% endif %}
        {{ form.closedate.label_tag }}<br>
        {{ form.closedate }}

        {{ form.media }}
        {% buttons %}
            <button name="submit"  class="w-100 btn btn-lg btn-primary" style="margin-top: 10px">Сохранить</button>
        {% endbuttons %}
    </form>
    <div class="d-flex justify-content-center">
            <a class="btn btn-sm btn btn-secondary" href="{% url 'project:filteredsubcashes' %}?c={{ cashregister }}">&#x21b6; Вернуться</a>
    </div>

{% endblock content %}

project/templates/project/archive.html
{% extends 'main/base.html' %}
{% block title %}
{{ title }}
{% endblock %}
{% load bootstrap_icons %}

{% block content %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container"  style="background-color:powderblue;">
                <div>
                    <h1>Архивные заявки</h1>
                </div>
{#                <div class="collapse navbar-collapse w-100 order-3 dual-collapse2" style="min-width: 300px"> #}
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
{#                            <a class="nav-link active" href="/bids/add">   #}
                            <a class="btn btn-secondary active" href="/bids/add">
                                {% bs_icon 'clipboard-plus' size='1.5em' color='white' extra_classes='mb-1' %}
                                <span class="fs-7 fw-semibold float-right">Добавить</span>
                            </a>
                        </li>


                    </ul>
 {#               </div> #}
            </div>
        </nav>
    {% if myarchive %}
        <div class="list-group list-group-flush border-bottom scrollarea" style="overflow-y: auto; background-color:powderblue;">
        {% for item in myarchive %}
            {% if item.highlighted %}
                <a href="{% url 'project:onearchiveitem' item.id %}?page={{ page }}" class="list-group-item list-group-item-action list-group-item-warning py-2 lh-tight">
            {% else %}
                <a href="{% url 'project:onearchiveitem' item.id %}?page={{ page }}" class="list-group-item list-group-item-action list-group-item-success py-2 lh-tight">
            {% endif %}
            <div class="d-flex w-100 align-items-center justify-content-between">
                <strong class="mb-1"><span class="badge rounded-pill bg-warning">{{ item.number }}</span><span class="badge rounded-pill bg-info">{{ item.object.name }}</span>{{ item.title }}</strong>
                <small>({{ item.owner.username }}) {{ item.date|date:"d/m/Y" }}
                        {% bs_icon 'box-seam' size='1.3em' color='gray' extra_classes='pl-3 mb-1' %}
                </small>

            </div>
        </a>
        {% endfor %}
            <nav aria-label="...">
                <ul class="pagination justify-content-center mt-3">
                    {% if page_.has_previous %}
                    <li class="page-item">
                    {% else %}
                    <li class="page-item disabled">
                    {% endif %}
                        <a class="page-link" href="/archive/?page={{ page|add:-1 }}">Предыдущая</a>
                    </li>
                    <li class="page-item active" aria-current="page">
                        <span class="page-link">{{page_.number}} из {{pages.num_pages}}</span>
                    </li>
                    {% if page_.has_next %}
                    <li class="page-item">
                    {% else %}
                    <li class="page-item disabled">
                    {% endif %}
                        <a class="page-link" href="/archive/?page={{ page|add:1 }}">Следующая</a>
                    </li>
                </ul>
            </nav>
        </div>

    {% else %}
        <h3 class="mb-3 mt-3">Вы пока ещё не подавали заявок</h3>
    {% endif %}
{% endblock %}

project/templates/project/editarch.html
{% extends 'main/base.html' %}
{% load bootstrap5 %}
{% block title %}
{{ title }}
{% endblock %}
{% load bootstrap_icons %}


{% block content %}
    <form method="post" class="form" style="max-width: 25em; padding: 15px; width: 100%; margin: auto">
        {% csrf_token %}
        <h1 class="h3 fw-normal" style="margin-top: 10px; margin-bottom: 10px">Корректировка архивной заявки №{{ arch.number }} по объекту {{ arch.object.name }}</h1>

        {# {% bootstrap_form form layout="vertical" size="small" show_label=True %} #}

        {{ form.number.label_tag }}<br>
        {{ form.number }}
        {% if form.number.errors %}
            <div class="alert alert-danger fade show mt-0" role="alert">{{ form.number.errors }}</div>
        {% endif %}
        {{ form.title.label_tag }}<br>
        {{ form.title }}

        {# {{ form.media }} #}


        {% buttons %}
            <button name="submit"  class="w-100 btn btn-lg btn-primary" style="margin-top: 10px">Сохранить</button>
        {% endbuttons %}
    </form>
    <div class="d-flex justify-content-center">
            <a class="btn btn-sm btn btn-secondary" href="{% url 'project:onearchiveitem' arch.id %}?page={{ page }}&q={{ number }}">{% bs_icon 'reply' size='1.5em' color='white' extra_classes='mb-1' %} Вернуться</a>
    </div>
{% endblock %}

project/templates/project/editbid.html
{% extends 'main/base.html' %}
{% load bootstrap5 %}
{% block title %}
{{ title }}
{% endblock %}
{% load bootstrap_icons %}


{% block content %}
    <form method="post" class="form" style="max-width: 25em; padding: 15px; width: 100%; margin: auto">
        {% csrf_token %}
        <h1 class="h3 fw-normal" style="margin-top: 10px; margin-bottom: 10px">Корректировка заявки №{{ bid.number }} по объекту {{ bid.object.name }}</h1>

        {# {% bootstrap_form form layout="vertical" size="small" show_label=True %} #}

        {% if error %}
                <div class="alert alert-danger fade show mt-0" role="alert">{{ error }}</div>
        {% endif %}

        {{ form.number.label_tag }}<br>
        {{ form.number }}
        {% if form.number.errors %}
            <div class="alert alert-danger fade show mt-0" role="alert">{{ form.number.errors }}</div>
        {% endif %}
        {{ form.title.label_tag }}<br>
        {{ form.title }}

        {# {{ form.media }} #}


        {% buttons %}
            <button name="submit"  class="w-100 btn btn-lg btn-primary" style="margin-top: 10px">Сохранить</button>
        {% endbuttons %}
    </form>
    <div class="d-flex justify-content-center">
            <a class="btn btn-sm btn btn-secondary" href="{% url 'project:onebid' bid.id %}?{{ rollback }}">{% bs_icon 'reply' size='1.5em' color='white' extra_classes='mb-1' %} Вернуться</a>
    </div>
{% endblock %}

project/templates/project/editexpense.html
{% extends 'main/base.html' %}
{% load static %}
{% load bootstrap5 %}
{% block title %}
{{ title }}
{% endblock %}
{% block mycss %} <style> .readonlyfield {border: 1px solid #ced4da; border-radius: .25rem; padding: .375rem 2.25rem .375rem .75rem; background-color: #FAFAFA} </style> {% endblock %}


{% block content %}
    <form method="post" class="form" style="max-width: 25em; padding: 15px; width: 100%; margin: auto">
        {% csrf_token %}
        <h3 class="h3 fw-normal" style="margin-top: 10px; margin-bottom: 10px">Корректировка расходной операции по кассе {{ cashreg.name }}</h3>
            Номер заявки:<br>
            <div class="readonlyfield">
                {{ content.bid.number }}
            </div>
            Объект:<br>
            <div class="readonlyfield">
                {{ content.bid.object.name }}
            </div>
            Дом:<br>
            <div class="readonlyfield">
                {{ content.house.name }}
            </div>
            Описание (материала/работ/вида техники):<br>
            <div class="readonlyfield">
                {{ content.title }}
            </div>
            Дата работ/поставки:<br>
            <div class="readonlyfield">
                {{ content.date|date:"d/m/Y" }}
            </div>
            Вид расходов:<br>
            <div class="readonlyfield">
                {{ content.get_type_display }}
            </div>
            Нал/б.нал/бартер:<br>
            <div class="readonlyfield">
                {{ content.get_cash_display }}
            </div>
            Количество:<br>
            <div class="readonlyfield">
                {{ content.quantity }}
            </div>
            Ед. измерения:<br>
            <div class="readonlyfield">
                {{ content.get_measure_display }}
            </div>
            Стоимость за ед.:<br>
            <div class="readonlyfield">
                {{ content.price }}
            </div>
            Поставщик:<br>
            <div class="readonlyfield">
                {{ content.supplier.name }}
            </div>
            Этап строительства:<br>
            <div class="readonlyfield">
                {{ content.phase.name }}
            </div>
            Смета:<br>
            <div class="readonlyfield">
                {{ content.estimate.name }}
            </div>
            Комментарий:<br>
            <div class="readonlyfield">
                {{ content.comment }}
            </div>
        {{ form.subcash.label_tag }}<br>
        {{ form.subcash }}
        {#<fieldset disabled>#}
        {{ form.expense_account.label_tag }}<br>
        {{ form.expense_account }}
        {{ form.credit_account.label_tag }}<br>
        {{ form.credit_account }}
        {#</fieldset>#}
        {{ form.media }}
        {% buttons %}
            <button name="submit"  class="w-100 btn btn-lg btn-primary" style="margin-top: 10px">Сохранить</button>
        {% endbuttons %}
    </form>
     <div class="d-flex justify-content-between" style="max-width: 330px; margin: auto; padding-left: 15px; padding-right: 15px;">
            <a class="btn btn-sm btn btn-secondary" href="{% url 'project:filteredbalances' %}?{{ rollback }}">&#x21b6; Вернуться</a>&nbsp;
            <a class="confirm-erase btn btn-sm btn btn-warning" href="{% url 'project:eraseexpensetransaction' content.id %}?{{ rollback }}">&#x2612; Сброс счетов</a>&nbsp;
    </div>
    <script type="text/javascript">
        $(document).on('click', '.confirm-erase', function(){
                return confirm('Вы действительно хотите очистить счета в этом документе?');
            })
    </script>
{% endblock content %}

project/templates/project/editsubcash.html
{% extends 'main/base.html' %}
{% load bootstrap5 %}
{% block title %}
{{ title }}
{% endblock %}
{% block mycss %} <style> .readonlyfield {border: 1px solid #ced4da; border-radius: .25rem; padding: .375rem 2.25rem .375rem .75rem; background-color: #FAFAFA} </style> {% endblock %}

{% block content %}
    <form method="post" class="form" style="max-width: 25em; padding: 15px; width: 100%; margin: auto">
        {% csrf_token %}
        <h1 class="h3 fw-normal" style="margin-top: 10px; margin-bottom: 10px">Корректировка кассы</h1>

        {{ form.name.label_tag }}<br>
        {{ form.name }}
        {#{{ form.cashregister.label_tag }}<br>#}
        {#{{ form.cashregister }}#}
        Относится к кассе:<br>
         <div class="readonlyfield">
             {{ cashregister_ }}
         </div>
        {{ form.balance.label_tag }}<br>
        {{ form.balance }}
        {{ form.date.label_tag }}<br>
        {{ form.date }}
        {% if form.date.errors %}
            <div class="alert alert-danger fade show mt-0" role="alert">{{ form.date.errors }}</div>
        {% endif %}
        {{ form.closedate.label_tag }}<br>
        {{ form.closedate }}

        {{ form.media }}
        {% buttons %}
            <button name="submit"  class="w-100 btn btn-lg btn-primary" style="margin-top: 10px">Сохранить</button>
        {% endbuttons %}
    </form>
    <div class="d-flex justify-content-center">
            <a class="btn btn-sm btn btn-secondary" href="{% url 'project:filteredsubcashes' %}?c={{ cashregister }}">&#x21b6; Вернуться</a>
    </div>

{% endblock content %}

project/templates/project/editturnovercomment.html
{% extends 'main/base.html' %}
{% load bootstrap5 %}
{% block title %}
{{ title }}
{% endblock %}
{% block mycss %} <style> .readonlyfield {border: 1px solid #ced4da; border-radius: .25rem; padding: .375rem 2.25rem .375rem .75rem; background-color: #FAFAFA} </style> {% endblock %}


{% block content %}
    <form method="post" class="form" style="max-width: 25em; padding: 15px; width: 100%; margin: auto">
        {% csrf_token %}
        <h1 class="h3 fw-normal" style="margin-top: 10px; margin-bottom: 10px">Корректировка операции по контракту</h1>

        {% if error %}
            <div class="alert alert-danger fade show mt-0" role="alert">{{ error }}</div>
        {% endif %}

        <div class="readonlyfield">
            <b>Контракт:</b> от {{ contract.date|date:"d/m/Y" }} {{ contract.get_type_display }}-{{ contract.number }} {{ contract.object.name }}/{{ contract.house.name }}/{{ contract.apartment }}
        </div>
        <div class="readonlyfield">
            <b>Дата операции:</b> {{ turnover.date|date:"d/m/Y" }}
        </div>
        <div class="readonlyfield">
            <b>{{ turnover.get_type_display }}</b> на сумму {{ turnover.amount }}
        </div>

        {{ form.comment.label_tag }}<br>
        {{ form.comment }}

        {{ form.media }}

        {% buttons %}
            <button name="submit"  class="w-100 btn btn-lg btn-primary" style="margin-top: 10px">Сохранить</button>
        {% endbuttons %}
    </form>
    <div class="d-flex justify-content-center">
            <a class="btn btn-secondary" href="{% url 'project:onecontract' contract.id %}{% if rollback %}?{{ rollback }}{% endif %}">&#x21b6; Вернуться</a>&nbsp;&nbsp;
    </div>
{% endblock %}