FreeDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('', include('project.urls')),
]


main/urls.py
from django.urls import path
from . import views
from django.conf.urls import url


urlpatterns = [
    path('', views.index, name='home'),
    path('about', views.about, name='about'),
    # path('add', views.add, name='add'),
]

project/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from .views import HousesAutocomplete
from .views import SuppliersAutocomplete
from dal import autocomplete
from .models import Goods
from .models import Object
from .models import House
from .models import Supplier

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'project'


class LinkedDataView(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return House.objects.none()

        qs = House.objects.all()
        object_ = self.forwarded.get('object', None)

        if object_:
            qs = qs.filter(object_id=object_)

        return qs


urlpatterns = [
    url(
        r'^goods-autocomplete/$',
        autocomplete.Select2QuerySetView.as_view(model=Goods),
        # GoodsAutocomplete.as_view(),
        name='select_goods',
    ),
    url(
        r'^objects-autocomplete/$',
        autocomplete.Select2QuerySetView.as_view(model=Object),
        # GoodsAutocomplete.as_view(),
        name='select_object',
    ),
    url(
        r'^houses-autocomplete/$',
        # autocomplete.Select2QuerySetView.as_view(model=House),
        HousesAutocomplete.as_view(),
        name='select_house',
    ),
    url(
        r'^suppliers-autocomplete/$',
        #autocomplete.Select2QuerySetView.as_view(model=Supplier),
        #SuppliersAutocomplete.as_view(create_field='name'),
        SuppliersAutocomplete.as_view(),
        name='select_supplier',
    ),
    url(
        r'^suppliers-autocomplete-view/$',
        SuppliersAutocomplete.as_view(),
        name='select_supplier_view',
    ),
    url(
        '^linked_data/$',
        LinkedDataView.as_view(model=House),
        name='linked_data'
    ),

    path('requests/<int:request_id>/add/', views.details_add, name='detailsadd'),
    path('requests/<int:request_id>/', views.one_request, name='onerequest'),
    path('requests/add', views.new_request, name='newrequest'),
    path('requests/', views.requests, name='requests'),

    path('content/<int:content_id>/delete/', views.contents_delete, name='contentsdelete'),
    path('content/<int:content_id>/edit/', views.contents_edit, name='contentsedit'),
    path('content/<int:content_id>/copy/', views.contents_copy, name='contentscopy'),
    path('content/<int:content_id>/expense/', views.edit_expense_transaction, name='editexpensetransaction'),
    path('content/<int:content_id>/erase/', views.erase_expense_transaction, name='eraseexpensetransaction'),

    path('bids/<int:bid_id>/edit/', views.bid_edit, name='bidedit'),
    path('bids/<int:bid_id>/delete/', views.bid_del, name='biddel'),
    path('bids/<int:bid_id>/report/', views.bid_report, name='bidreport'),
    path('bids/<int:bid_id>/unlock/', views.bid_unlock, name='bidunlock'),
    path('bids/<int:bid_id>/mark/', views.bid_mark, name='bidmark'),
    path('bids/<int:bid_id>/unmark/', views.bid_unmark, name='bidunmark'),

    path('bids/<int:bid_id>/hide/', views.bid_hide, name='bidhide'),
    path('bids/<int:bid_id>/unhide/', views.bid_unhide, name='bidunhide'),

    path('bids/<int:bid_id>/refund/', views.bid_refund, name='bidrefund'),
    path('bids/<int:bid_id>/cancel/', views.bid_cancel_refund, name='bidcancelrefund'),

    path('bids/<int:bid_id>/sign/', views.bid_sign, name='bidsign'),
    path('bids/<int:bid_id>/lock/', views.bid_lock, name='bidlock'),
    path('bids/<int:bid_id>/add/', views.contents_add, name='contentsadd'),
    path('bids/<int:bid_id>/delivery/', views.bid_delivery, name='biddelivery'),
    path('bids/<int:bid_id>/', views.one_bid, name='onebid'),
    path('bids/add/', views.new_bid, name='newbid'),
    path('bids/', views.filtered_bids, name='bids'),

    path('contract/<int:contract_id>/image/<int:image_id>/', views.view_image, name='viewimage'),
    path('contract/<int:contract_id>/image/<int:image_id>/del/', views.delete_image, name='deleteimage'),

    path('turnover/<int:turnover_id>/goback/', views.turnover_return_perform, name='turnoverreturnperform'),
    path('turnover/<int:turnover_id>/bid/', views.turnover_bid_create, name='turnoverbidcreate'),
    path('turnover/<int:turnover_id>/expense/', views.turnover_expense, name='turnoverexpense'),
    path('turnover/<int:turnover_id>/delete/', views.turnover_delete, name='turnoverdelete'),
    path('turnover/<int:turnover_id>/accept/', views.turnover_accept, name='turnoveraccept'),
    path('turnover/<int:turnover_id>/return/', views.turnover_return, name='turnoverreturn'),
    path('turnover/<int:turnover_id>/perform/', views.edit_turnover_perform, name='turnovereditperform'),
    path('turnover/<int:turnover_id>/edit/', views.edit_turnover, name='turnoveredit'),
    path('turnover/<int:turnover_id>/comment/', views.edit_turnover_comment, name='turnovercommentedit'),
    path('contract/<int:contract_id>/report/', views.contract_report, name='contractreport'),
    path('contract/<int:contract_id>/return/', views.contract_return, name='contractreturn'),
    path('contract/<int:contract_id>/delete/', views.contract_delete, name='contractdelete'),
    path('contract/<int:contract_id>/open/', views.contract_open, name='contractopen'),
    path('contract/<int:contract_id>/performed/', views.contract_performed, name='contractperformed'),
    path('contract/<int:contract_id>/execute/', views.contract_execute, name='contractexecute'),
    path('contract/<int:contract_id>/onreserve/', views.contract_reservation, name='contractreservation'),
    path('contract/<int:contract_id>/unreserve/', views.contract_unreservation, name='contractunreservation'),
    path('contract/<int:contract_id>/reserve/', views.contract_reservation_accept, name='contractreserveaccept'),
    path('contract/<int:contract_id>/takeout/', views.contract_reservation_takeout, name='contractreservetakeout'),
    path('contract/<int:contract_id>/accept/', views.contract_accept, name='contractaccept'),
    path('contract/<int:contract_id>/turnover/', views.add_turnover, name='turnoveradd'),
    path('contract/<int:contract_id>/addimage/', views.add_checkimage, name='addcheckimage'),
    path('contract/<int:contract_id>/edit/', views.edit_contract, name='contractedit'),
    path('contract/<int:contract_id>/change/', views.change_contract, name='contractchange'),
    path('contract/<int:contract_id>/receipt/', views.receipt_contract, name='contractreceipt'),
    path('contract/<int:contract_id>/revoke/', views.revoke_contract, name='contractrevoke'),
    path('contract/<int:contract_id>/restore/', views.contract_restore, name='contractrestore'),
    path('contract/<int:contract_id>/', views.one_contract, name='onecontract'),
    path('contracts/add/', views.new_contract, name='contractadd'),
    path('contracts/', views.filtered_contracts, name='contracts'),

    path('contractsexport/', views.contracts_export, name='contractsexport'),
    path('bidsexport/', views.bids_export, name='bidsexport'),
    #path('transferobject/', views.transfer_object, name='transferobject'),
    #path('fill_delivered_bids/', views.fill_delivered_bids_, name='fill_delivered_bids'),
    #path('fill_performed_turnovers/', views.fill_performed_turnovers_, name='fill_performed_turnovers'),
    #path('fill_completed_contracts/', views.fill_completed_contracts_, name='fill_completed_contracts'),

    path('detail/<int:detail_id>/edit/', views.details_edit, name='detailsedit'),
    path('detail/<int:detail_id>/delete/', views.details_delete, name='detailsdelete'),
    path('archive/<int:arch_id>/delete/', views.arch_delete, name='archdelete'),
    path('archive/<int:arch_id>/edit/', views.arch_edit, name='archedit'),
    path('archive/<int:arch_id>/', views.one_archive_item, name='onearchiveitem'),
    path('archive/', views.archive, name='archive'),

    path('prepayment/<int:prepayment_id>/edit/', views.prepayment_edit, name='prepaymentedit'),
    path('prepayment/add/', views.new_prepayment, name='newprepayment'),
    path('concrete/<int:delivery_id>/edit/', views.concrete_delivery_edit, name='concretedeliveryedit'),
    path('concrete/<int:delivery_id>/delete/', views.concrete_delivery_delete, name='concretedeliverydelete'),
    path('concrete/add/', views.new_concrete_delivery, name='newdconcretedelivery'),
    path('concrete/', views.filtered_concrete_delivery, name='filteredconcretedelivery'),

    path('balances/', views.filtered_balances, name='filteredbalances'),
    path('subcash/<int:subcash_id>/edit/', views.edit_subcash, name='subcashedit'),
    path('subcash/add/', views.new_subcash, name='newsubcash'),
    path('subcash/', views.filtered_subcashes, name='filteredsubcashes'),

    path('earning/<int:earning_id>/edit/', views.edit_earning_transaction, name='editearningtransaction'),
    path('earning/add/', views.create_earning_transaction, name='newearning'),
    path('account/<int:account_id>/edit/', views.edit_account, name='accountedit'),
    path('account/add/', views.new_account, name='newaccount'),
    path('account/', views.filtered_accounts, name='filteredaccounts'),

    path('report/house/<int:house_id>/<int:estimate_id>/<int:phase_id>/<str:type>/<str:exclusion>/', views.house_estimate_report, name='houseestimatereport'),
    path('phasereport/house/<int:house_id>/<int:phase_id>/<int:estimate_id>/<str:type>/<str:exclusion>/', views.house_phase_report, name='housephasereport'),
    path('report/house/<int:house_id>/concrete/', views.house_concrete_report, name='houseconcretereport'),
    path('report/house/<int:house_id>/', views.house_report, name='housereport'),
    path('supplier/<int:supplier_id>/report', views.supplier_detail_xls_report, name='supplierdetailxlsreport'),


main/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Task(models.Model):
    title = models.CharField('Название', max_length=20)
    task = models.TextField('Задача')
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

main/forms.py
from .models import Task
from django.forms import ModelForm, TextInput, Textarea


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ["title", "task"]
        widgets = {
            "title": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите название'
            }),
            "task": Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Введите описание'
            }),
        }

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Task
from .forms import TaskForm
from dal import autocomplete



@login_required
def index(request):
    tasks = Task.objects.filter(owner=request.user).order_by('-id')  # filter(title__contains='экл')
    return render(request, 'main/index.html', {'title': 'Main page', 'tasks': tasks})


def about(request):
    return render(request, 'main/about.html')


@login_required
def add(request):
    error = ''
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            return redirect('home')
        else:
            error = 'Неверные данные формы'
    form = TaskForm()
    context = {
        'form': form,
        'error': error
    }
    return render(request, 'main/add.html', context)

main/templates/main/about.html
{% extends 'main/base.html' %}
{% block title %}
О сайте
{% endblock %}

{% block content %}
    <h1>О сайте</h1>
    <p>Тут что-то о сайте !</p>
{% endblock %}

main/templates/main/add.html
{% extends 'main/base.html' %}
{% block title %}
{{ title }}
{% endblock %}

{% block content %}
    <h1>Добавление новой задачи</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.title}}
        {{ form.task}}
        <button type="submit" class="btn btn-success">Добавить</button>
    </form>
{% endblock %}

main/templates/main/base.html
{% load bootstrap5 %}
{% load static %}

{% load tags %}

<!doctype html>
<html lang="en" style="scroll-behavior: unset">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <link src="{% static '/admin/css/base.css' %}" type="text/css" rel="stylesheet" />
    <link src="{% static '/admin/css/forms.css' %}" type="text/css" rel="stylesheet" />

{#     <link src="{% static '/admin/css/vendor/select2/select2.css' %}" type="text/css" rel="stylesheet" /> #}
{#     <link src="{% static '/admin/css/autocomplete.css' %}" type="text/css" rel="stylesheet" /> #}
{#     <link src="{% static '/autocomplete-light/select2.css' %}" type="text/css" rel="stylesheet" /> #}
       <script type="text/javascript" src="{% static '/admin/js/vendor/jquery/jquery.js' %}"></script>
{#     <script type="text/javascript" src="{% static '/admin/js/jquery.init.js' %}"></script> #}
{#     <script type="text/javascript" src="{% static '/bootstrap.min.js' %}"></script> #}

{#--    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> #}
{#    <script type="text/javascript" src="{% static '/jquery-3.6.0.min.js' %}"></script> #}
{#    <script type="text/javascript" src="{% static '/admin/js/vendor/select2/select2.full.js' %}"></script> #}
    <script type="text/javascript" src="{% static '/js/jquery.bootstrap.modal.forms.min.js' %}"></script>


    {% bootstrap_css %}
    {% bootstrap_javascript %}

    {% block mycss %} {% endblock mycss %}

</head>
<body>

<header class="p-2 bg-dark text-white">
    <div class="container">
      {#<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">#}
       <nav class="navbar navbar-expand-md bd-navbar justify-content-center">
        {#<div class="container-fluid">#}
        {#<div class="collapse navbar-collapse">#}
             {% is_boss request as is_boss_ %}
             {% is_supplier request as is_supplier_ %}
             {% is_accountant request as is_accountant_ %}
             {% is_manager request as is_manager_ %}
             {% is_only_seller request as is_only_seller_ %}
             {% is_seller request as is_seller_ %}
             {% is_concreter request as is_concreter_ %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
              {% if not is_only_seller_ %}
              <li class="nav-item">
                  <a href="{% url 'project:bids' %}" class="nav-link px-2 text-white">&#x1f3e0; Перечень заявок</a>
              </li>
              {% endif %}
             {% if is_manager_ or is_supplier_ or is_accountant_ or is_boss_ %}

                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle text-blue bg-dark" href="#" data-bs-toggle="dropdown" aria-expanded="true" role="button">
                         &#x1f4dd; Отчёты
                      </a>
                        <ul class="dropdown-menu bg-light" style="cursor: pointer">
                            <li><a href="{% url 'project:phasereport' %}" class="dropdown-item">Отчёт по расходам (по этапу)</a></li>
                            <li><a href="{% url 'project:report' %}" class="dropdown-item">Отчёт по расходам (по смете)</a></li>
                            <li><a href="{% url 'project:supplierreport' %}" class="dropdown-item">Отчёт по поставщикам за период</a></li>
                            <li><a href="{% url 'project:bidsexport' %}" class="dropdown-item">Выгрузка заявок в эксель</a></li>
                            <li><a href="{% url 'project:contractsexport' %}" class="dropdown-item">Выгрузка контрактов в эксель</a></li>
                            <li><a href="{% url 'project:archive' %}" class="dropdown-item"> Архив</a></li>
                            <li><a href="{% url 'project:orders' %}" class="dropdown-item"> Заказы</a></li>
                            {% if is_accountant_ or is_boss_ %}
                                <li><a href="{% url 'project:filteredbalances' %}" class="dropdown-item">Справка по кассе</a></li>
                            {% endif %}
                        </ul>
                </li>
              {% endif %}
             {% if is_concreter_ or is_manager_ %}
                <li>
                    <a href="{% url 'project:filteredconcretedelivery' %}" class="nav-link px-2 text-blue">&#x1f4e5; Бетон</a>
                </li>
             {% endif %}
             {% if is_seller_ %}
                <li>
                    <a href="{% url 'project:contracts' %}" class="nav-link px-2 text-blue">&#x1f4dc; Контракты</a>
                </li>
             {% endif %}

             {% is_boss request as is_boss_ %}
             {% is_supplier request as is_supplier_ %}
             {% is_accountant request as is_accountant_ %}
             {% if is_boss_ or is_supplier_ or is_accountant_ %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle text-blue bg-dark" href="#" data-bs-toggle="dropdown" aria-expanded="true" role="button">
                        &#9776;&nbsp;Справочники
                      </a>
                        <ul class="dropdown-menu bg-light" style="cursor: pointer">
                            <li><a href="{% url 'project:samples' %}" class="dropdown-item">Шаблоны заказов</a></li>
                            {% if is_boss_ %}
                                <li><a href="{% url 'project:objects' %}" class="dropdown-item">Объекты/дома</a></li>
                                <li><a href="{% url 'project:estimates' %}" class="dropdown-item">Сметы</a></li>
                                <li><a href="{% url 'project:phases' %}" class="dropdown-item">Этапы строительства</a></li>
                            {% endif %}
                             {% if is_boss_ or is_supplier_ or is_accountant_ %}
                                <li><a href="{% url 'project:suppliers' %}" class="dropdown-item">Поставщики</a></li>
                            {% endif %}
                             {% if is_boss_ or is_accountant_ %}
                                <li><a href="{% url 'project:filteredsubcashes' %}" class="dropdown-item">Кассы</a></li>
                                <li><a href="{% url 'project:filteredaccounts' %}" class="dropdown-item">Счета</a></li>
                            {% endif %}
                        </ul>
                </li>
             {% endif %}
              {% if not is_only_seller_ %}
                <li><a href="{% url 'project:found' %}" id="view-search" class="nav-link px-2 text-blue">&#128270; Поиск заявок</a></li>
              {% endif %}
            {% endif %}
          </ul>

        <div class="text-end">

            {% if user.is_authenticated %}
                 {{ user.username }}
                <a href="{% url 'users:logout' %}" class="btn btn-primary btn-lg active" role="button">Выйти</a>
            {% else %}
                <a href="{% url 'users:login' %}" class="btn btn-primary btn-lg active" role="button">Войти</a>
                {# <a href="{% url 'users:register' %}" class="login-btn btn btn-outline-light me-2">Sign up</a> #}
            {% endif %}
        </div>


        {#</div>#}
        {#</div>#}
      </div>
       </nav>

        {#<form action="{% url 'project:search' %}" method="get" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">#}
        {#  <input type="q" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">#}
        {#</form>#}
{#--#}
{#--#}
     {#</div>#}
    </div>
  </header>
    <div class="container">
        {% block content %}{% endblock %}
    </div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal-search">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>


  <footer>
      <p class="mt-5 mb-3 text-muted" align="center">© 2021</p>
  </footer>
</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block title %}
{{ title }}
{% endblock %}

{% block content %}
    <h1>Главная страница</h1>
    {% if tasks %}
    {% for item in tasks %}
        <div class="alert alert-success mt-2">
            <h3>{{ item.title }}</h3>
            <p>{{ item.task }}</p>
        </div>
    {% endfor %}
    {% else %}
        <p>Нет записей в БД!</p>
    {% endif %}
{% endblock %}